Linux test reorg
- split images into libfuse2 and libfuse3
- do not `apt` anything inside the tests
- run libfuse2 and libfuse3 commands as separate tests
- but put experimental tests into corresponding libfuse2 and libfuse3 tests
- check mount state before/after each test
- use `anyhow::Context` to show stack what exactly is failing, e.g.

```
Error: Tests with libfuse3 failed

Caused by:
    0: experimental mount tests failed
    1: Tests failed: --features=experimental fusermount=/bin/false
    2: Expecting single mount on dev hello, got mounts:
       Device mounts:
         hello /tmp/tmp.GtQRwDnURw fuse
         hello /tmp/.tmpGnQAYo fuse
```